language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false
dist: trusty

env:
  matrix:
    - NETCOMMONS_VERSION=master DB=mysql
  global:
      - secure: "LcT7Ivvh9s24ERAbryDL+/P7fS/k3EidAEcPZg2GFnCpmrMvTIBa/Gwe1PSugpHlBPBuMOmPTdPguZD93xyihb4kmjgRFaYSeAj+nByNjJIQQIAQr4zfy/DtzyGNw7tOaNlYfbMAARlMN5Ex/JEfXs088diJGGWSTBbnqkfRmBQ="
      - GIT_COMMITTER_NAME=RyujiAMANO
      - GIT_COMMITTER_EMAIL=ryuji@ryus.co.jp
      - GIT_AUTHOR_NAME=RyujiAMANO
      - GIT_AUTHOR_EMAIL=ryuji@ryus.co.jp

before_script:
  - export NETCOMMONS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/NetCommons3
  - git clone git://github.com/NetCommons3/NetCommons3 $NETCOMMONS_BUILD_DIR
  - cd $NETCOMMONS_BUILD_DIR
  - git checkout $NETCOMMONS_VERSION
  - travis_wait . tools/build/plugins/cakephp/travis/pre.sh
  - . tools/build/plugins/cakephp/travis/environment.sh

script:
  - . tools/build/plugins/cakephp/travis/main.sh

after_script:
  - . tools/build/plugins/cakephp/travis/post.sh
